name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install package dependencies
        run: flutter pub get

      - name: Install example dependencies
        working-directory: ./example
        run: flutter pub get

      - name: Check code formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Analyze package
        run: flutter analyze

      - name: Analyze example
        working-directory: ./example
        run: flutter analyze

      - name: Run package unit tests
        run: flutter test

      - name: Run example widget tests
        working-directory: ./example
        run: flutter test
